branches:
  except:
  - "/^wip/"
language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install --dev
script:
- pytest
- "./tests/functional.sh"
notifications:
  slack:
    secure: w4jyIgNqO0TFNpVtLYOhXNg5S5q6PLMZshBrwEZl8ldMty7RfVamq48TfSj9/sWO+cWzOBiZxAKX1s243k36FvjoKKgeTBFyvZTlXJr8setuI+gZzFESrVfyaTKJ4IbFkuY9AbAvggMaf816gDRH3s0hHCPnIjRHH0IrofmhxkStK0cULdpICDcIef0VyQ5k7eI9CAeBXX41C34Qe3hseurMnlZfJL7vqtE48FDyhuJ2FIqKmRoqAWh8ef8ogppo2rcwvIZM9ZyYLG1Z9upc29dNjF3lAKFPSVtYDg6YX8wlUhMZPHMtHG6/ENbFJ4+FL95zpG0giPTXCEwl+JE/ynzpzhB+usu0qEB+XYU4jwzNyG1hzxAe5ki3s+aUZXCRHDma/lyer4XBGO45Wv6Sao9epyTA+9UfDg7Q+E6kv4vyBOWfZI3pFm2KuiWHpjts7XwU/MB4Q8d2ZKQhgWeEoqFWYUNb7UulSRlAVBT8IHFNW6SiHlJ6inRfNmo4MOw6PipnJBYmGNoiwdCPNQgVuHOIYqkEOQ4r6y7mQgbJrOn1CO5o9jCJ+gSyKaDTcD8/jZE0vISXezPCeFgbzVdGxzAw1/VkgfweUohvhYk1zEuwAiPXJwLqL0dpiRmuYM1YDrECtBRAa5mxi3QZ2kjTJHTI0GGEvY6W0VyP3xm/gOg=

